### ISSUE TITLE
Is this compatible with Amazon S3(-like) storage?

### ISSUE THREAD

**Issue by sbarany** [Daniel-KM/Omeka-plugin-ArchiveRepertory#10]
When I try to configure, get error:
`Fatal error: Uncaught Error: Call to undefined method Omeka_Storage_Adapter_ZendS3::getOptions() in /var/www/media/plugins/ArchiveRepertory/ArchiveRepertoryPlugin.php:916 Stack trace: #0 /var/www/media/plugins/ArchiveRepertory/ArchiveRepertoryPlugin.php(128): ArchiveRepertoryPlugin->_getLocalStoragePath() #1 /var/www/media/application/libraries/Omeka/Plugin/Broker.php(142): ArchiveRepertoryPlugin->hookConfigForm() #2 /var/www/media/admin/themes/default/plugins/config.php(8): Omeka_Plugin_Broker->callHook() #3 /var/www/media/application/libraries/Omeka/View.php(114): include('/var/www/media/...') #4 /var/www/media/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run() #5 /var/www/media/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render() #6 /var/www/media/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript() #7 /var/www/media/application/libraries/Zend/Controller/Action/Helper/Vi in /var/www/media/plugins/ArchiveRepertory/ArchiveRepertoryPlugin.php on line 916`

**Comment by Daniel-KM** [comment]
No, it is not compatible with Amazon S3, but the Omeka S version supports it.

**Comment by timstallmann** [comment]
Working on addressing this via #12!
